name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v3
        with:
          name: Dumpostor.dll
          path: Dumpostor/bin/Release/net6.0/Dumpostor.dll

      - uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: Dumpostor/bin/Release/net6.0/Dumpostor.dll
